### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by HwaitingDK** [DebjitPramanick/Hotel-Booking-Web-App#1]
Your app get crashed whenever we try to book hotel

Url: https://hotel-booking-web-app.vercel.app/hotel/61e2ee97739991f1606c880c

**Comment by Harshu1121** [comment]
![Screenshot 2023-11-28 162855](https://github.com/DebjitPramanick/Hotel-Booking-Web-App/assets/121597969/55f239de-87ab-466e-afac-1f5a5e635f02)

actual  when i connected the project to mongo db and fire base  the database is not visible to me , though the hotel details are shown in the react app website    how should i get the data base details

**Comment by DebjitPramanick** [comment]
Maybe the API URL you are using in the project is the live url. So data is coming in the UI. Change the API url to localhost url of backend and start the app.
